version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.64.0
    steps:
      - checkout
      - run: cargo --version
      - run: cargo install --path .
      - run: cargo build
      - run: bash -c 'echo "ElliottLandsborough" | rust-terminal-app'
